package com.herotraining.data.notifications

import android.content.Context
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.herotraining.HeroApp
import com.herotraining.data.ai.GeminiClient

/**
 * WorkManager worker that fires at a scheduled time (via setInitialDelay) and
 * shows the mentor notification. The push text is generated by Gemini in the
 * voice of the currently-selected hero (falls back to a static default if
 * the AI call fails or no hero is chosen yet).
 *
 * Input data:
 *   KEY_KIND = KIND_NUTRITION / KIND_TRAINING — determines prompt + notification id
 *
 * Why a worker (not AlarmManager):
 *   - We tolerate ±15 min jitter ("герои не ждут" allows some fuzziness)
 *   - WorkManager respects battery/doze without us wiring BroadcastReceivers
 *   - Guaranteed to run eventually even if deferred — won't be lost
 */
class MentorPushWorker(
    appContext: Context,
    params: WorkerParameters
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val kind = inputData.getString(KEY_KIND) ?: return Result.failure()
        val app = applicationContext.applicationContext as? HeroApp
        val state = app?.stateRepository?.snapshot()
        val heroName = state?.hero?.name

        val (title, body) = generate(kind, heroName)

        val notifId = when (kind) {
            KIND_NUTRITION -> HeroNotifications.NOTIF_NUTRITION_MORNING
            KIND_TRAINING -> HeroNotifications.NOTIF_TRAINING_UNLOCK
            else -> HeroNotifications.NOTIF_TEST
        }
        HeroNotifications.showMentor(applicationContext, notifId, title, body)
        return Result.success()
    }

    /**
     * Returns (short title, full body). Title is a hook that shows in the status bar;
     * body expands when user pulls down the notification.
     */
    private suspend fun generate(kind: String, heroName: String?): Pair<String, String> {
        val (titleFallback, bodyFallback) = staticFallback(kind, heroName)

        // If Gemini not configured or call fails — use static text, never crash the worker.
        if (!GeminiClient.isConfigured) return titleFallback to bodyFallback

        val prompt = buildPrompt(kind, heroName)
        val result = runCatching { GeminiClient.mentorGreeting(heroName) }
            .getOrNull()?.getOrNull()

        // mentorGreeting returns "[model] text" — strip the prefix if present
        val clean = result?.substringAfter("] ", result)?.trim()

        return if (!clean.isNullOrBlank()) {
            // Split the generated line into a hook + full — first sentence is the push title
            val firstSentence = clean.substringBefore('.').take(60).ifBlank { titleFallback }
            firstSentence to clean
        } else {
            titleFallback to bodyFallback
        }
    }

    private fun buildPrompt(kind: String, heroName: String?): String {
        val persona = heroName?.let { "Ты — наставник '$it' из приложения Протокол Героя." } ?: ""
        val context = when (kind) {
            KIND_NUTRITION -> "Сейчас 06:00 утра. Разблокировался план питания на день. " +
                "Напиши короткий пуш-мессидж (1-2 фразы) который воин увидит на локскрине — нужно " +
                "заинтересовать открыть приложение. В характере персонажа. Хук в первой фразе. " +
                "Намекни что план питания ждёт. Не пиши markdown."
            KIND_TRAINING -> "Сейчас 10:00. Первая тренировка разблокирована. " +
                "Короткий пуш-мессидж (1-2 фразы) в характере. Заряди боем. Первая фраза — хук. " +
                "Не пиши markdown."
            else -> "Короткий дружеский пинок чтоб воин вернулся в приложение."
        }
        return "$persona\n\n$context"
    }

    private fun staticFallback(kind: String, heroName: String?): Pair<String, String> = when (kind) {
        KIND_NUTRITION -> "План питания готов" to
            (heroName?.let { "$it: завтрак ждёт. Открой приложение — сегодня едим как надо." }
                ?: "Открой приложение — план питания на сегодня готов.")
        KIND_TRAINING -> "Время первой миссии" to
            (heroName?.let { "$it: первая тренировка разблокирована. Давай." }
                ?: "Тренировка дня разблокирована.")
        else -> "Протокол Героя" to "Возвращайся в приложение."
    }

    companion object {
        const val KEY_KIND = "kind"
        const val KIND_NUTRITION = "nutrition"
        const val KIND_TRAINING = "training"
    }
}
